// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stageygqbwhhscpkvxqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0YWdleWdxYndoaHNjcGt2eHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTM2MjgsImV4cCI6MjA3MDMyOTYyOH0.V4B1NxUxLgsrPDS4HIWIqVEyWz19f0Ge6YB4esBJW3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});